name: Rust_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: rust_sqllite #change this to the rust project name you are developing.

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Check
      run: cargo check
      working-directory: ${{ env.WORKING_DIR }}

    - name: Lint
      run: cargo clippy
      working-directory: ${{ env.WORKING_DIR }}

    - name: Format
      run: cargo fmt
      working-directory: ${{ env.WORKING_DIR }}

    - name: Test
      run: cargo test --test test
      working-directory: ${{ env.WORKING_DIR }}

    - name: Release
      run: cargo build --release
      working-directory: ${{ env.WORKING_DIR }}

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4 #v3 is scheduled for deprecation Nov 30 2024 check marketplace
      with:
        name: RuSQLite CLI Binary
        path: ${{ env.WORKING_DIR }}/target/release/rust_sqllite #change the /add to the name of your binary